[project]
requires-python = ">=3.10"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["ANN", "B", "C","E", "F", "W", "I", "N", "UP"]
exclude = ["venv", ".git", "__pycache__", "**/__init__.py"]
ignore = ["E712", "UP017"]