[project]
requires-python = ">=3.10"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["A", "C","E", "F", "W", "I", "UP"]

aggressive = true
exclude = ["venv", ".git", "__pycache__", "**/__init__.py"]

ignore = ["C0111", "E1102", "E712", "UP017"]